# Generated by Django 3.2.8 on 2021-11-25 06:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mdeditor.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0c71e5d4-6293-4885-83af-57548b6eeb8a'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('displayName', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('avatar', models.ImageField(blank=True, upload_to='avatar')),
                ('host', models.URLField(default='http://cmput404-team13-socialapp.herokuapp.com', max_length=64)),
                ('url', models.URLField(default='http://cmput404-team13-socialapp.herokuapp.com/author/', max_length=100)),
                ('github', models.CharField(blank=True, max_length=100)),
                ('followers', models.ManyToManyField(blank=True, to='socialapp.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('e998b884-39fd-4020-909a-4be746ac2c31'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialapp.author')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('21e2fbf3-e8b7-4a7b-aaec-8bbb10806cec'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='', max_length=140)),
                ('description', models.CharField(default='', max_length=140)),
                ('contentType', models.CharField(default='PLAIN', max_length=30)),
                ('content', mdeditor.fields.MDTextField()),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('visibility', models.CharField(default='PUBLIC', max_length=30)),
                ('unlisted', models.BooleanField(default=False)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialapp.author')),
                ('inbox', models.ManyToManyField(blank=True, to='socialapp.Inbox')),
                ('likes', models.ManyToManyField(blank=True, related_name='post_likes', to='socialapp.Author')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(default='Like', max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialapp.author')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialapp.post')),
            ],
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('62ba08da-b454-4823-8b33-c169e77ad761'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialapp.author')),
                ('inbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socialapp.inbox')),
                ('object', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frieqnd_request_object', to='socialapp.author')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('7e4bd786-b1f4-426c-be79-f75240e91443'), editable=False, primary_key=True, serialize=False, unique=True)),
                ('comment', models.CharField(max_length=140)),
                ('contentType', models.CharField(default='PLAIN', max_length=30)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialapp.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialapp.post')),
            ],
        ),
    ]
