# Generated by Django 3.1.6 on 2021-10-27 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inbox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialapp.author')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='inbox',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialapp.inbox'),
        ),
    ]
