# Generated by Django 3.2.8 on 2021-11-25 07:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_auto_20211125_0642'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categories',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='origin',
            field=models.URLField(default='https://cmput404-team13-socialapp.herokuapp.com/'),
        ),
        migrations.AddField(
            model_name='post',
            name='source',
            field=models.URLField(default='https://cmput404-team13-socialapp.herokuapp.com/'),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6a4f1165-871f-4de0-aa58-647b9bd9b910'), editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
