# Generated by Django 3.2.8 on 2021-10-27 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_auto_20211027_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='inbox',
        ),
        migrations.AddField(
            model_name='inbox',
            name='friend_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socialapp.friendrequest'),
        ),
        migrations.AddField(
            model_name='inbox',
            name='type',
            field=models.CharField(default='friend_request', max_length=32),
        ),
    ]
