# Generated by Django 3.2.8 on 2021-10-26 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_auto_20211025_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content_type',
            new_name='contentType',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='date',
            new_name='published',
        ),
    ]
