# Generated by Django 3.2.8 on 2021-10-26 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0003_auto_20211026_0244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='comment',
            name='contentType',
            field=models.CharField(default='PLAIN', max_length=30),
        ),
    ]
