# Generated by Django 3.2.8 on 2021-10-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0004_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='friends_only',
            field=models.BooleanField(default=False),
        ),
    ]
